---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r libraries, message = FALSE,warning=FALSE}
library(mice)
library(ggplot2)
library(dplyr)
library(mi)
library(mice)
library(devtools)
library(mitools)
library(SensMiceDA)
```


```{r Load Data}
data(CHAIN)
summary(CHAIN)
```



```{r Data Wrangling}
# Data Wrangling
MyData <- CHAIN[apply(CHAIN, 1, function(x) !all(is.na(x))), ]


# VL_binary is a binary variable 
# 0: viral load < 500 c/mL 
# 1: viral load >= 500 c/mL

MyData$VL_binary <- NA
MyData$VL_binary <- ifelse((MyData$log_virus < log(500) & !is.na(MyData$log_virus)),0, MyData$VL_binary)
MyData$VL_binary <- ifelse((MyData$log_virus >= log(500) & !is.na(MyData$log_virus)),1, MyData$VL_binary)

# Data Wrangling
MyData_new <- MyData %>% dplyr::select(-log_virus) %>%
  mutate(treatment = as.factor(treatment),
         damage = as.factor(damage),
         mental = as.factor(mental),
         VL_binary = as.factor(VL_binary))
```


```{r Compltete Case analysis}
fit_complete <- glm(mental ~., data = MyData_new, family = binomial)
summary(fit_complete)

MyData_comp <- na.omit(MyData_new)

MyData_comp %>% group_by(VL_binary) %>%
  tally()
```



```{r Multiple Imputation (MAR)}
# Implement Multiple Imputation
MyData_imp <- mice(MyData_new, method = c("pmm", "pmm", "pmm", "logreg",
"polyreg", "polyreg", "logreg"), seed = 1234)

# Store each imputed dataset
MyData_imp_1 <- mice::complete(MyData_imp, 1)
MyData_imp_2 <- mice::complete(MyData_imp, 2)
MyData_imp_3 <- mice::complete(MyData_imp, 3)
MyData_imp_4 <- mice::complete(MyData_imp, 4)
MyData_imp_5 <- mice::complete(MyData_imp, 5)

# Put in a list
MyData_imp_all <- mitools::imputationList(list(MyData_imp_1, MyData_imp_2,
                                      MyData_imp_3,MyData_imp_4, MyData_imp_5))
```


```{r Fit a glm model}
# Fit a glm model
fit_1 <- with(MyData_imp_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))

# Coeffcients
coef_fit_1 <- MIextract(fit_1, fun=coef)

# Covariance
var_fit_1 <- MIextract(fit_1, fun=vcov)

# Organize coefficents and covariance
res_fit_1 <- summary(MIcombine(coef_fit_1, var_fit_1))

# Deviance
dev_fit_1 <- MIextract(fit_1, fun=deviance)



# Calcualte p-value
fit_2 <- with(MyData_imp_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           #as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))

dev_fit_2 <- MIextract(fit_2, fun=deviance)
summary(fit_1)
p_value_fit_1 <- mean(1-pchisq(unlist(dev_fit_2)-unlist(dev_fit_1), 1))
p_value_fit_1

```

## Theta = 1.2
```{r}
# Imputation with a supplementary parameter 1.2 on the VL2cat variable
MyData_imp_new <- sens.mice(MyData_imp, ListMethod = c("", "", "","", "", "", "MyFunc"), SupPar = c(1.2))

# Construction of the completed imputed data sets
MyData_imp_new_1 <- mice::complete(MyData_imp_new, 1)
MyData_imp_new_2 <- mice::complete(MyData_imp_new, 2)
MyData_imp_new_3 <- mice::complete(MyData_imp_new, 3)
MyData_imp_new_4 <- mice::complete(MyData_imp_new, 4)
MyData_imp_new_5 <- mice::complete(MyData_imp_new, 5)


MyData_imp_new_all <- imputationList(list(MyData_imp_new_1, MyData_imp_new_2,
                                          MyData_imp_new_3, MyData_imp_new_4, 
                                          MyData_imp_new_5))




fit_new_1 <- with(MyData_imp_new_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))


coef_fit_new_1 <- MIextract(fit_new_1, fun=coef)
var_fit_new_1 <- MIextract(fit_new_1, fun=vcov)
res_fit_new_1 <- summary(MIcombine(coef_fit_new_1, var_fit_new_1))
dev_fit_new_1 <- MIextract(fit_new_1, fun=deviance)

fit_new_2 <- with(MyData_imp_new_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           #as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))


dev_fit_new_2 <- MIextract(fit_new_2, fun=deviance)
pvalVL2cat.SCEN1 <- mean(1-pchisq(unlist(dev_fit_new_2)- unlist(dev_fit_new_1), 1))
```




## Theta = 1.5
```{r}
# Imputation with a supplementary parameter 1.2 on the VL2cat variable
MyData_imp_new <- sens.mice(MyData_imp, ListMethod = c("", "", "","", "", "", "MyFunc"), SupPar = c(1.5))

# Construction of the completed imputed data sets
MyData_imp_new_1 <- mice::complete(MyData_imp_new, 1)
MyData_imp_new_2 <- mice::complete(MyData_imp_new, 2)
MyData_imp_new_4 <- mice::complete(MyData_imp_new, 3)
MyData_imp_new_3 <- mice::complete(MyData_imp_new, 4)
MyData_imp_new_5 <- mice::complete(MyData_imp_new, 5)


MyData_imp_new_all <- imputationList(list(MyData_imp_new_1, MyData_imp_new_2,
                                          MyData_imp_new_3, MyData_imp_new_4, 
                                          MyData_imp_new_5))




fit_new_1 <- with(MyData_imp_new_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))


coef_fit_new_1 <- MIextract(fit_new_1, fun=coef)
var_fit_new_1 <- MIextract(fit_new_1, fun=vcov)
res_fit_new_1 <- summary(MIcombine(coef_fit_new_1, var_fit_new_1))
dev_fit_new_1 <- MIextract(fit_new_1, fun=deviance)

fit_new_2 <- with(MyData_imp_new_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           #as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))


dev_fit_new_2 <- MIextract(fit_new_2, fun=deviance)
pvalVL2cat.SCEN1 <- mean(1-pchisq(unlist(dev_fit_new_2)- unlist(dev_fit_new_1), 1))
```


# theta = 1.8
```{r}
# Imputation with a supplementary parameter 1.2 on the VL2cat variable
MyData_imp_new <- sens.mice(MyData_imp, ListMethod = c("", "", "","", "", "", "MyFunc"), SupPar = c(1.8))

# Construction of the completed imputed data sets
MyData_imp_new_1 <- mice::complete(MyData_imp_new, 1)
MyData_imp_new_2 <- mice::complete(MyData_imp_new, 2)
MyData_imp_new_3 <- mice::complete(MyData_imp_new, 3)
MyData_imp_new_4 <- mice::complete(MyData_imp_new, 4)
MyData_imp_new_5 <- mice::complete(MyData_imp_new, 5)


MyData_imp_new_all <- imputationList(list(MyData_imp_new_1, MyData_imp_new_2,
                                          MyData_imp_new_3, MyData_imp_new_4, 
                                          MyData_imp_new_5))




fit_new_1 <- with(MyData_imp_new_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))


coef_fit_new_1 <- MIextract(fit_new_1, fun=coef)
var_fit_new_1 <- MIextract(fit_new_1, fun=vcov)
res_fit_new_1 <- summary(MIcombine(coef_fit_new_1, var_fit_new_1))
dev_fit_new_1 <- MIextract(fit_new_1, fun=deviance)

fit_new_2 <- with(MyData_imp_new_all, glm(mental ~ as.numeric(age) +
                                           as.numeric(healthy) + 
                                           as.numeric(damage) + 
                                           as.factor(income) + 
                                           #as.factor(VL_binary) +
                                           as.factor(treatment), 
                                           family=binomial))


dev_fit_new_2 <- MIextract(fit_new_2, fun=deviance)
pvalVL2cat.SCEN1 <- mean(1-pchisq(unlist(dev_fit_new_2)- unlist(dev_fit_new_1), 1))
```

